### PR TITLE
Fix `next.config.js` resolution

### LINKED ISSUE #24: Support `next.config.js` in parent directories
In a monorepo setup, it is possible that `next.config.js` might be in a parent directory if the user has set a `base` directory.
Next.js is searching `next.config.js` in parent directories using [`find-up`](https://github.com/sindresorhus/find-up):

https://github.com/vercel/next.js/blob/497cac4b93de9ecf6c7ed79bd6557dcd3bb51be5/packages/next/next-server/server/config.ts#L450

However we are not currently searching it in parent directories:

https://github.com/netlify/netlify-plugin-nextjs/blob/2849dc5f7c57e9fd827a939e067a871e4cb487b1/index.js#L57

Using `find-up` should fix this bug.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #24

In a monorepo setup, it is possible that `next.config.js` might be in a parent directory if the user has set a `base` directory.
Next.js is searching `next.config.js` in parent directories using [`find-up`](https://github.com/sindresorhus/find-up):

https://github.com/vercel/next.js/blob/497cac4b93de9ecf6c7ed79bd6557dcd3bb51be5/packages/next/next-server/server/config.ts#L450

However we are not currently searching it in parent directories:

https://github.com/netlify/netlify-plugin-nextjs/blob/2849dc5f7c57e9fd827a939e067a871e4cb487b1/index.js#L57

Using `find-up` should fix this bug.

This also adds a test for it.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -120,21 +120,24 @@ describe('preBuild()', () => {
...
-      constants: { FUNCTIONS_SRC: 'out_functions' },
-    })
-    restoreCwd()
-
-    const acceptableTargets = ['serverless', 'experimental-serverless-trace']
-    expect(utils.build.failBuild.mock.calls[0][0]).toEqual(
-      `next.config.js must be one of: ${acceptableTargets.join(', ')}`,
-    )
-  })
+  test.each(['invalid_next_config', 'deep_invalid_next_config'])(
```
Comment (lindsaylevine) [inline test/index.js:123]: :O

File: test/index.js [hunk 2]
```diff
@@ -120,21 +120,24 @@ describe('preBuild()', () => {
...
+        utils,
+        constants: { FUNCTIONS_SRC: 'out_functions' },
+      })
+      restoreCwd()
+
+      const acceptableTargets = ['serverless', 'experimental-serverless-trace']
+      expect(utils.build.failBuild.mock.calls[0][0]).toEqual(
+        `next.config.js must be one of: ${acceptableTargets.join(', ')}`,
+      )
+    },
```
Comment (lindsaylevine) [inline test/index.js:139]: friendly reminder to update this with the new fixture and failBuild logic whenever you merge everything :) <3

**Review by lindsaylevine — APPROVED** [review]

File: test/index.js (hunk 2 above)
Comment (ehmicky) [reply test/index.js:132]: Rebased and fixed! :+1:
