### PR TITLE
fix: refactor image function

### LINKED ISSUE #307: Support for GIF and SVG in next/image
cc @maximeheckel

### PR DESCRIPTION
**Pull request by ascorbic**
This is a rewrite of the image function. The main fixes are improved error handling and new logic to determine output format. The logic for choosing the output format is as follows:

1. Determine the format of the input image by examining the buffer
2. If the format is SVG or GIF then we do not process it at all, so we redirect to the source image
3. If the format is unsupported (i.e. not JPEG, PNG, WebP or AVIF) then we fall-back to JPEG output
4. If the env var `FORCE_WEBP_OUTPUT` is set, then set output format to WebP. 
5. Otherwise, output format is the same as input format.
Fixes #307 and #312

### CODE REVIEW

File: src/lib/templates/imageFunction.js [hunk 1]
```diff
@@ -1,52 +1,95 @@
...
+
+  const type = getImageType(bufferData)
+
+  if (!type) {
+    return { statusCode: 400, body: 'Source does not appear to be an image' }
+  }
+
+  let { ext } = type
+
+  // For unsupported formats (gif, svg) we redirect to the original
```
Comment (lindsaylevine) [inline src/lib/templates/imageFunction.js:61]: 🔥

File: src/lib/templates/imageFunction.js [hunk 2]
```diff
@@ -1,52 +1,95 @@
...
+  if (process.env.FORCE_WEBP_OUTPUT) {
+    ext = 'webp'
+  }
+
+  if (!OUTPUT_FORMATS.has(ext)) {
+    ext = 'jpg'
+  }
+
+  // The format methods are just to set options: they don't
+  // make it return that format.
```
Comment (lindsaylevine) [inline src/lib/templates/imageFunction.js:80]: oh huh ok!!!!!

**Review by lindsaylevine — APPROVED** [review]
amazing!!!!!!! i think this might also fix https://github.com/netlify/netlify-plugin-nextjs/issues/133 which i forgot about until i saw the env var?! just added the label to it - lmk what you think and/or comment on it if you see fit!!!
