### PR TITLE
fix: try to resolve next modules via multiple paths

### LINKED ISSUE #475: Next canary's changed directory structure breaks imports
**Describe the bug**
Next.js has recently changed the directory structure, which breaks some of our deep imports. This is just in the canary for now, but when released it will break builds.

- `https://github.com/vercel/next.js/pull/26734`
- `https://github.com/vercel/next.js/pull/26756`

### PR DESCRIPTION
**Pull request by ascorbic**
Next.js recently changed its directory structure, which broke our deep imports ( #475 ). This PR adds support to `resolveNextModule` for passing arrays of paths, to allow backward-compatible updates to paths like these. Meanwhile it also adds integration tests against `next@canary` to make this less likely to happen. We also have plans to add automatic tests against new canary releases.

Fixes #475

### CODE REVIEW

File: helpers/getNextConfig.js [hunk 1]
```diff
@@ -13,7 +13,10 @@ const getNextConfig = async function (failBuild = defaultFailBuild, cwd = getCwd
   // site is using `next` inside `onPreBuild`.
   /* eslint-disable import/no-dynamic-require */
   const { PHASE_PRODUCTION_BUILD } = require(resolveNextModule('next/constants', cwd))
-  const loadConfig = require(resolveNextModule('next/dist/next-server/server/config', cwd)).default
+  const loadConfig = require(resolveNextModule(
+    ['next/dist/next-server/server/config', 'next/dist/server/config'],
+    cwd,
+  )).default
```
Comment (lindsaylevine) [inline helpers/getNextConfig.js:19]: NICE

File: helpers/resolveNextModule.js [hunk 2]
```diff
@@ -1,13 +1,31 @@
...
+        console.log('resolved', resolved)
+        return resolved
+      }
+    } catch (error) {
+      // Failed. Trying next.
+    }
+  }
+
+  throw new Error(`Could not resolve Next module. Tried "${modules.join(', ')}"`)
 }
```
Comment (lindsaylevine) [inline helpers/resolveNextModule.js:29]: ez

**Review by lindsaylevine — COMMENTED** [review]
awesome!!! 

my only thought is that maybe we should add consts that indicate that
`next/dist/next-server/...` was < next 11.x (or whatever it was) and `next/dist/server` is >= canary ?

**Review by lindsaylevine — APPROVED** [review]
!
