### PR TITLE
fix: correct redirect priority and correctly handle ISR pages assets

### LINKED ISSUE #765: [Bug]: `/api` routes remove the query parameters on the req object
### Steps to reproduce

use the latest beta.4 or beta.5 version of netlify-plugin-nextjs v4
and add a file called test.js in the pages/api with the following content:

```js
export default async function test(req, res) {
  res.status(200).json({query: req.query})
}

```

then deploy on netl;ify and test the route.. `/api/test?foo=pbar`

the result is 
```json
 {"query":{}}
``` 
and it shoud be 
```json
 {"query":{"foo":"pbar"}}
```

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Mac OS

### Your `netlify.toml` file

```shell
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

### other Relevant info: 

When i downgrade back to 3.9.2 it works again..

### PR DESCRIPTION
**Pull request by ascorbic**
### Summary

Corrects the ordering of rewrites, and adds one to ensure api routes aren't served by ODBs. Also ensures that pre-rendered ISR pages aren't served from the CDN, as they need to be handled by the function.

### Test plan

1. Visit the [the deploy preview api route](https://deploy-preview-826--netlify-plugin-nextjs-demo.netlify.app/api/hello?anyparam=anything) and ensure that the query is echoed back
2. Visit [a revalidate page](https://deploy-preview-826--netlify-plugin-nextjs-demo.netlify.app/getStaticProps/withRevalidate/1/) and check in the network panel that the header `x-render-mode` is `ssr` and the `date` header is now. (Don't expect the render time in the page to update)

### Relevant links (GitHub issues, Notion docs, etc.) or a picture of cute animal

Fixes #765 

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

File: demo/pages/index.js [hunk 1]
```diff
@@ -4,29 +4,18 @@ const Header = dynamic(() => import(/* webpackChunkName: 'header' */ '../compone
 import { useRouter } from 'next/router'
```
Comment (ascorbic) [inline demo/pages/index.js:4]: These are just some updates to the demo index page, as it used deprecated syntax

**Review by lukasholzer — APPROVED** [review]
LGTM
